version: '3'

services:
  pi_watcher:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WEBHOOK_URL=YOUR WEBHOOK URL
      - RSS_URL=YOUR RPILOCATOR RSS FEED URL
      - USER_AGENT=Hogbisz Pi pi_watcher
      - FREQUENCY=5
    restart: 'unless-stopped'
